language: rust
cache:
  directories:
  - $HOME/.cargo/bin
rust:
  - nightly
before_script:
  - rustup component add --toolchain nightly rustfmt-preview
  - export PATH=$PATH:$HOME/.cargo/bin/
script:
  - scripts/check_format.sh
  - scripts/build_and_test.sh
