language: rust
env:
  global:
    - RUSTFMT_VERSION=0.5.0
cache:
  directories:
  - $HOME/.cargo/bin
rust:
  - nightly
before_script:
  - if [ ! -f $HOME/.cargo/bin/rustfmt ]; then cargo install rustfmt --vers $RUSTFMT_VERSION; else echo "rustfmt already installed"; fi
  - export PATH=$PATH:$HOME/.cargo/bin/
script:
  - scripts/check_format.sh
  - scripts/build_and_test.sh
